server:
  port: 29308
  host: localhost

spring:
  application:
    name: qrsignature

  datasource:
    url: jdbc:sqlite:qrsignature.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  data:
    redis:
      host: 10.219.24.10
      port: 6379
      password:
      database: 8
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

jwt:
  secret: qrsignature-secret-key-2024-for-jwt-token-generation-and-validation
  expiration: 900000  # 15分钟 in milliseconds

logging:
  level:
    com.qrsignature: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"